#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

# Make install script executable
chmod +x $OPENSHIFT_REPO_DIR/misc/install.sh > /dev/null 2>&1